### ISSUE TITLE
POG

### ISSUE THREAD

**Issue by Pukimaa** [Project-Browser/Spotify-Enhanced#1]
I am excited ^^

**Comment by hwalker928** [comment]
No need to make an issue for that..

**Comment by Pukimaa** [comment]
> No need to make an issue for that..

psst...

**Comment by Pukimaa** [comment]
Also I would recommend checking out `spicetify -cli` for some inspirstion

**Comment by TheRealGWJosh** [comment]
I'll Check It Out But Don't Joke Around
